import { describe, it, expect, afterAll } from 'vitest';
import { loadConfig } from '../../src/config/load';
import { GitHubCopilotAgentConnector } from '../../src/agents/GitHubCopilotAgentConnector';
import { InMemoryWorkTrackingConnector } from '../../src/worktracking/fakes/InMemoryWorkTrackingConnector';
import { FakeLlmAdapter } from '../../src/llm/fakes/FakeLlmAdapter';
import { RecordingCommunicationAdapter } from '../../src/comms/fakes/RecordingCommunicationAdapter';
import { Planner } from '../../src/llm/Planner';
import { AgentMemory } from '../../src/memory/AgentMemory';
import { InMemoryStorage } from '../../src/memory/InMemoryStorage';
import { Orchestrator } from '../../src/orchestrator/Orchestrator';

const config = loadConfig();
const token = config.agent.provider === 'github-copilot' ? config.agent.github.token : undefined;
const assignee = config.agent.github.owner ?? 'davidwhitney';

// Throwaway repo for garbage created by these tests.
const REPO = 'davidwhitney/junkrepo';
const createdIssues: number[] = [];

async function gh(path: string, init?: RequestInit): Promise<Response> {
  return fetch(`https://api.github.com${path}`, {
    ...init,
    headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json', ...init?.headers },
  });
}

// Clean up every issue we opened (best effort).
afterAll(async () => {
  if (!token) return;
  for (const number of createdIssues) {
    await gh(`/repos/${REPO}/issues/${number}`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ state: 'closed', state_reason: 'not_planned' }),
    }).catch(() => undefined);
  }
});

describe.skipIf(!token)('GitHub integration (junkrepo)', () => {
  it('dispatches a real issue and reads its status back', async () => {
    const connector = new GitHubCopilotAgentConnector({ token, assignee });

    const result = await connector.dispatch({
      repository: REPO,
      prompt: '[smoke] integration test issue — safe to close, no action needed.\nGenerated by the test suite.',
      workItem: { connector: 'jira', projectId: 'SMOKE', id: 'smoke', key: 'SMOKE-1' },
    });

    expect(result.agentRunId).toMatch(/^davidwhitney\/junkrepo#\d+$/);
    const number = Number(result.agentRunId.split('#')[1]);
    createdIssues.push(number);

    const issue = (await (await gh(`/repos/${REPO}/issues/${number}`)).json()) as {
      state: string;
      title: string;
    };
    expect(issue.state).toBe('open');
    expect(issue.title).toContain('SMOKE-1');

    // No PR opened against it yet, so the run is still in progress.
    const status = await connector.getStatus(result.agentRunId);
    expect(status.state).toBe('in_progress');
  });

  it('runs a full dispatch cycle end-to-end (fake plan, real GitHub issue)', async () => {
    const tracker = new InMemoryWorkTrackingConnector();
    tracker.seed({ id: 'smoke-e2e', projectId: 'SMOKE', key: 'SMOKE-2', title: 'end-to-end smoke', tags: ['agent-ready'] });

    const agent = new GitHubCopilotAgentConnector({ token, assignee });
    const planner = new Planner(
      new FakeLlmAdapter(() =>
        JSON.stringify({ repositories: [REPO], prompt: '[smoke] e2e — safe to close', summary: 'smoke' }),
      ),
    );
    const comms = new RecordingCommunicationAdapter();
    const memory = new AgentMemory(new InMemoryStorage());
    const orchestrator = new Orchestrator({ connectors: [tracker], planner, agent, memory, comms });

    const summary = await orchestrator.runDispatchCycle();
    expect(summary).toMatchObject({ considered: 1, dispatched: 1, failed: 0 });

    const record = (await memory.all())[0]!;
    createdIssues.push(Number(record.runs[0]!.agentRunId.split('#')[1]));

    // The orchestrator advanced the ticket and recorded the dispatch.
    expect(record.status).toBe('dispatched');
    expect(tracker.get('smoke-e2e')!.tags).toContain('agent-acting');
    expect(comms.typesSeen()).toContain('dispatched');
  });
});
